version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: desapegai-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wln@h1n1
      POSTGRES_DB: desapegai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
